import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme/themeProvider";
import NavMain from "@/components/nav/navMain";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Footer from "@/components/footer/footer";
import ClientwhatsappComponent from "@/components/whatsapp/DynamicWhatsapp";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const fontSans = Red_Hat_Text({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-sans",
});
export default async function RootLayout({
	children,
	params: { slug },
}: Readonly<{
	children: React.ReactNode;
	params: { slug: string };
}>) {
	const messages = await getMessages();

	return (
		<html lang={slug} suppressHydrationWarning={true}>
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased !mr-0",
					fontSans.variable,
				)}
			>
				<NextIntlClientProvider messages={messages}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<NavMain slug={slug} />

						{children}
						<ClientwhatsappComponent />
						<Footer />
					</ThemeProvider>
				</NextIntlClientProvider>
				<Toaster />
			</body>
		</html>
	);
}
