import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme/themeProvider";
import NavMain from "@/components/nav/navMain";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const fontSans = Red_Hat_Text({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-sans",
});
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable,
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<NavMain />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
